export const artistList = [
  {
    card: "yanncard.webp",
    picture: "yann.svg",
    firstName: "Yann",
    pseudo: "@arsene.ariel",
    description: "Arsène Ariel esquisse en noir et gris des images empreintes de mélancolie, où l’esthétique circassienne et le romantisme se mêlent à une influence traditionnelle.",
    key: 1,
  },
  {
    card: "alicecard.webp",
    picture: "alice.svg",
    firstName: "Alice",
    pseudo: "@lullaby.ttt",
    description: "Lullaby fusionne amour et morbide dans une esthétique creepycute teintée de poésie. Son style en constante évolution donne vie à des œuvres troublantes et touchantes.",
    key: 2,
  },
  {
    card: "damiencard.webp",
    picture: "damien.svg",
    firstName: "Damien",
    pseudo: "@kaolin.ttt",
    description: "Inspiré par les bleus cobalt de la porcelaine, Kaolin transforme les motifs céramiques en tatouages raffinés. Son style transmet la délicatesse des lignes classiques, réinterprétées avec finesse et modernité.",
    key: 3,
  },
  {
    card: "agathecard.webp",
    picture: "agathe.svg",
    firstName: "Agathe",
    pseudo: "@poupeekipikdamour",
    description: "Poupeekipikdamour tisse à main levée des ornements spontanés directement sur la peau. Elle lie avec tendresse art nouveau, formes libres et inspirations végétales.",
    key: 4,
  },
  {
    card: "leacard.webp",
    picture: "lea.svg",
    firstName: "Léa",
    pseudo: "@leclair_ttt",
    description: "L’éclair compose des abstractions subtiles, alliant médiums graphiques et extraits de ses propres photographies urbaines ou végétales. Un travail autour du corps, des lignes et des courbes.",
    key: 5,
  },
  {
    card: "martincard.webp",
    picture: "martin.svg",
    firstName: "Martin",
    pseudo: "@10.tattoo",
    description: "Dice explore la calligraphie et l’ornementation comme un langage intemporel. Inspiré par les symboles ancestraux et l’abstraction, il trace des compositions rigoureuses où formes et lettres s’entrelacent avec précision.",
    key: 6,
  },
  {
    card: "zoecard.webp",
    picture: "zoe.svg",
    firstName: "Zoé",
    pseudo: "@zozita.slowpoke",
    description: "Par la douceur du handpoke, Zozita inscrit sur la peau des motifs délicats et symboliques. Son travail marie ésotérisme, ornementation et géométrie sacrée.",
    key: 7,
  },
  {
    card: "inacard.webp",
    picture: "ina.svg",
    firstName: "Ina",
    pseudo: "@aim_dessire",
    description: "Inna associe son goût pour les motifs floraux et tribaux à un univers plus personnel, astral et surréaliste. Son trait épuré mêle abstraction et narration, créant des tatouages oniriques à la fois évocateurs et sensibles.",
    key: 8,
  },
];

