export const artistList = [
  {
    card: "yanncard.webp",
    picture: "yann.svg",
    firstName: "Yann",
    pseudo: "@arsene.ariel",
    description: "Ceci est une description.",
    key: 1,
  },
  {
    card: "alicecard.webp",
    picture: "alice.svg",
    firstName: "Alice",
    pseudo: "@lullaby.ttt",
    description: "Ceci est une description.2",
    key: 2,
  },
  {
    card: "damiencard.webp",
    picture: "damien.svg",
    firstName: "Damien",
    pseudo: "@kaolin.ttt",
    description: "Ceci est une description.3",
    key: 3,
  },
  {
    card: "agathecard.webp",
    picture: "agathe.svg",
    firstName: "Agathe",
    pseudo: "@poupeekipikdamour",
    description: "Ceci est une description.4",
    key: 4,
  },
  {
    card: "leacard.webp",
    picture: "lea.svg",
    firstName: "Léa",
    pseudo: "@leclair_ttt",
    description: "Ceci est une description.5",
    key: 5,
  },
  {
    card: "martincard.webp",
    picture: "martin.svg",
    firstName: "Martin",
    pseudo: "@10.tattoo",
    description: "Ceci est une description.6",
    key: 6,
  },
  {
    card: "zoecard.webp",
    picture: "zoe.svg",
    firstName: "Zoé",
    pseudo: "@zozita.slowpoke",
    description: "Ceci est une description.7",
    key: 7,
  },
  {
    card: "inacard.webp",
    picture: "ina.svg",
    firstName: "Ina",
    pseudo: "@aim_dessire",
    description: "Ceci est une description.8",
    key: 8,
  },
];

